/// <reference path="c:\users\ivayla\documents\visual studio 2013\Projects\JS-AMD-And-RequireJs-Homework\JS-AMD-And-RequireJs-Homework\libs/jquery-2.1.1.js" />
/// <reference path="c:\users\ivayla\documents\visual studio 2013\Projects\JS-AMD-And-RequireJs-Homework\JS-AMD-And-RequireJs-Homework\libs/handlebars.js" />
/*globals window, document console*/

define(['jQuery', 'handlebars'], function (_jQ, handlebars) {
    console.log('inside comboBox.js');
    var controls = {};

    // constructor for ComboBox, the only property it has is the array of people
    var ComboBox = function (items) {
        this.items = items;
    }

    // applying the Handlebars template to each of the array elements
    ComboBox.prototype.render = function (templateContent) {
        var template, $dropDown, $currentElement, i, len;

        template = Handlebars.compile(templateContent);
        $dropDown = $('<div />');
        $dropDown.addClass('drop-down-list');

        for (i = 0, len = this.items.length; i < len; i += 1) {
            $currentElement = $(template(this.items[i]));
            if (i === 0) {
                $currentElement.addClass(' selected');
            }
            console.log($currentElement);
            $dropDown.append($currentElement);
        }

        // attach evenets to the elements
        makeDropDownMenu.call($dropDown);

        return $dropDown;
    }

    // this function attaches the events to the HTML elements generated by the ComboBox.render()
    function makeDropDownMenu() {
        var $self, $personItems, $selectedItem;

        $self = this;
        $personItems = $self.find('.person-item');
        $selectedItem = $self.find('.person-item.selected');

        $personItems.hide();
        $selectedItem.show();
        console.log($selectedItem);
    
        $self.on('click', 'div', function () {
            var $clicked, $currentlySelected;;

            $clicked = $(this);
            $currentlySelected = $($self.find('.selected'));

            console.log($clicked);
            console.log($currentlySelected);

            if ($clicked.html() === $currentlySelected.html()) {
                $personItems.show();
            } else{
                $currentlySelected.removeClass('selected');

                $clicked.addClass('selected');
                $personItems.hide();
                $clicked.css('display', '');
            }
        });

        return $self;
    }

    // used to create an instance of the ComboBox
    controls.ComboBox = function (itemsSource) {
        return new ComboBox(itemsSource);
    }

    return controls;
});